name: expandtesting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  

      - name: Step 1 Install NPM
        run: npm install

      - name: Step 2 Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Step 3 Execute collection
        run: bru run --env expandtesting_env --output ../reports/report.json

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: report
            path: ./reports/report.json